/**
 * Builds the built-in levels from their authoring sources (`scripts/author/<world>.ts`):
 * compiles each reference plan, sets the ★★ master threshold to what the reference run saves and
 * the ★★★ frugal threshold to its number of assignments ("beat the designer"), writes
 * `src/levels/<world>/NN.json` and regenerates the level texts (`src/i18n/levels.*.ts`).
 * Run: `npm run levels:author [world…]`. Fails when a plan does not win.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ThemeId } from '../src/core/level';
import { compilePlan } from '../src/levels/plan';
import type { WorldId } from '../src/levels/validate';
import { type LevelSpec, toLevel } from './author/build';
import { W1 } from './author/w1';
import { LEVELS_DIR, writeLevelFile } from './levelFiles';

interface WorldSource {
  id: WorldId;
  theme: ThemeId;
  levels: LevelSpec[];
}

const SOURCES: WorldSource[] = [{ id: 'w1', theme: 'glade', levels: W1 }];

const only = new Set(process.argv.slice(2));
const en: Record<string, string> = {};
const hu: Record<string, string> = {};
let broken = 0;

for (const world of SOURCES) {
  const dir = join(LEVELS_DIR, world.id);
  mkdirSync(dir, { recursive: true });
  for (const spec of world.levels) {
    const level = toLevel(world.id, world.theme, spec);
    en[`level.${level.id}.title`] = spec.title[0];
    hu[`level.${level.id}.title`] = spec.title[1];
    spec.hints?.forEach((h, i) => {
      en[`level.${level.id}.hint${i + 1}`] = h[0];
      hu[`level.${level.id}.hint${i + 1}`] = h[1];
    });
    if (only.size > 0 && !only.has(world.id) && !only.has(level.id)) continue;
    const r = compilePlan(level, spec.plan);
    const assigns = r.solution.log.filter((c) => c.kind === 'assign').length;
    const ok = r.won && r.unfired.length === 0;
    if (!ok) broken++;
    console.log(
      `${ok ? '✓' : '✗'} ${level.id} "${spec.title[0]}": saved ${r.saved}/${level.creatures} ` +
        `(need ${level.required}), ${assigns} skills, ${r.ticks} ticks` +
        (r.unfired.length ? `, unfired steps ${r.unfired.join(',')}` : ''),
    );
    const idle = compilePlan(level, []);
    if (idle.won) console.log(`    ! ${level.id} is solvable without any skill`);
    level.master = Math.max(level.required, r.saved);
    level.frugal = assigns;
    level.solution = r.solution;
    writeLevelFile(join(dir, `${String(spec.index).padStart(2, '0')}.json`), {
      ...level,
      plan: spec.plan,
    });
  }
}

const header = (lang: string): string =>
  `/** Generated by \`npm run levels:author\` from scripts/author/*.ts – do not edit (${lang}). */\n`;
const body = (o: Record<string, string>): string =>
  Object.entries(o)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
const i18n = join(LEVELS_DIR, '..', 'i18n');
writeFileSync(
  join(i18n, 'levels.en.ts'),
  `${header('EN')}export const levelsEn = {\n${body(en)}\n} as const;\n`,
);
writeFileSync(
  join(i18n, 'levels.hu.ts'),
  `${header('HU')}import type { levelsEn } from './levels.en';\n\nexport const levelsHu: Record<keyof typeof levelsEn, string> = {\n${body(hu)}\n};\n`,
);
process.exit(broken > 0 ? 1 : 0);
