import type { LevelObject } from '../../src/core/level';
import {
  CRUMBLE,
  type LevelSpec,
  METAL,
  ONEWAY_L,
  ONEWAY_R,
  ROCK,
  SOIL,
  cut,
  each,
  entrance,
  exitOn,
  lava,
  range,
  rect,
  sideWalls,
  stamp,
  water,
} from './build';

/**
 * Bonus pool (§1.3, T5.6): 30 extra levels across all four themes, difficulty 1–10. The daily
 * level picks one of them per UTC day with a modifier (−1 of a skill, −60 s, +1 required); the
 * author script records a reference solution for every modifier a level survives, and the stocks
 * leave a little slack on purpose so most levels support several modifiers.
 */

const W = 320;
const FLOOR = 440;
const walls = sideWalls(W, 0, 480);
const soilFloor = rect(SOIL, 0, FLOOR, W, 40);
const rockFloor = rect(ROCK, 0, FLOOR, W, 40);
const BIG = { w: 480, h: 720 };
const bigWalls = sideWalls(480, 0, 720);

function trapOn(x: number, groundY: number): LevelObject {
  return { type: 'trap', x, y: groundY - 10 };
}

function padOn(x: number, groundY: number): LevelObject {
  return { type: 'bounce', x, y: groundY - 4 };
}

function portal(x: number, groundY: number, tx: number, ty: number): LevelObject {
  return { type: 'teleport', x, y: groundY - 12, tx, ty };
}

function both(ids: readonly number[]) {
  return ids.flatMap((i) => [
    { assign: 'scaler' as const, creature: i, when: { state: 'walk' as const } },
    { assign: 'glider' as const, creature: i, when: { state: 'walk' as const } },
  ]);
}

export const BONUS: LevelSpec[] = [
  {
    index: 1,
    title: ['Garden Gate', 'Kertkapu'],
    hints: [
      ['Dig down, then let the wall turn them home.', 'Áss le, a fal majd hazafordítja őket.'],
    ],
    theme: 'glade',
    difficulty: 1,
    ops: [soilFloor, rect(SOIL, 0, 380, W, 40), ...walls],
    objects: [entrance(160, 370), exitOn(60, FLOOR)],
    creatures: 10,
    required: 7,
    skills: { delver: 2 },
    plan: each('delver', [0], { xGte: 200 }),
  },
  {
    index: 2,
    title: ['Pebble Steps', 'Kavicslépcső'],
    hints: [['One staircase is all it takes.', 'Egyetlen lépcső elég.']],
    theme: 'deep',
    difficulty: 1,
    ops: [rockFloor, rect(ROCK, 200, 430, W - 200, 10), ...walls],
    objects: [entrance(40, 430), exitOn(280, 430)],
    creatures: 10,
    required: 8,
    skills: { mason: 2 },
    plan: each('mason', [0], { xGte: 178 }),
  },
  {
    index: 3,
    title: ['Double Wall', 'Dupla fal'],
    hints: [['Two walls, two tunnels.', 'Két fal, két alagút.']],
    theme: 'clockworks',
    difficulty: 2,
    ops: [soilFloor, rect(SOIL, 120, 360, 16, 80), rect(SOIL, 220, 360, 16, 80), ...walls],
    objects: [entrance(40, 430), exitOn(285, FLOOR)],
    creatures: 10,
    required: 9,
    skills: { burrower: 3 },
    plan: [...each('burrower', [0], { xGte: 112 }), ...each('burrower', [0], { xGte: 212 })],
  },
  {
    index: 4,
    title: ['Feather Fall', 'Pihekönnyű'],
    hints: [['Every leaf counts.', 'Minden levél számít.']],
    theme: 'skyreach',
    difficulty: 2,
    ops: [soilFloor, rect(SOIL, 0, 220, 130, 16), stamp('cloud', SOIL, 40, 216), ...walls],
    objects: [entrance(40, 210), exitOn(270, FLOOR)],
    creatures: 10,
    required: 7,
    skills: { glider: 10 },
    minReleaseTicks: 50,
    plan: each('glider', range(10)),
  },
  {
    index: 5,
    title: ['Pond Hop', 'Tóugrás'],
    hints: [['Go under the pond, not through it.', 'A tó alatt menj át, ne rajta keresztül.']],
    theme: 'glade',
    difficulty: 2,
    ops: [soilFloor, rect(SOIL, 0, 360, W, 60), cut(170, 360, 60, 20), ...walls],
    objects: [entrance(40, 350), exitOn(285, FLOOR), water(170, 362, 60, 18)],
    creatures: 10,
    required: 8,
    skills: { sloper: 2 },
    plan: each('sloper', [0], { xGte: 110 }),
  },
  {
    index: 6,
    title: ['Ore Vein', 'Érctelér'],
    hints: [
      [
        'Three layers – start each shaft a little further on.',
        'Három réteg – minden aknát kicsit odébb kezdj.',
      ],
    ],
    theme: 'deep',
    difficulty: 3,
    ops: [
      rockFloor,
      rect(SOIL, 0, 260, W, 30),
      rect(ROCK, 0, 320, W, 30),
      rect(SOIL, 0, 380, W, 30),
      ...walls,
    ],
    objects: [entrance(60, 250), exitOn(270, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 4 },
    plan: [
      ...each('delver', [0], { xGte: 100 }),
      ...each('delver', [0], { xGte: 140, yGte: 320 }),
      ...each('delver', [0], { xGte: 180, yGte: 380 }),
    ],
  },
  {
    index: 7,
    title: ['Turnstile', 'Forgókereszt'],
    hints: [['Skip the trap: take the stairs down.', 'Kerüld ki a csapdát: lefelé vezet az út.']],
    theme: 'clockworks',
    difficulty: 3,
    ops: [soilFloor, rect(SOIL, 0, 380, W, 40), stamp('gear', METAL, 250, 330), ...walls],
    objects: [entrance(40, 370), trapOn(200, 380), exitOn(280, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 2 },
    plan: each('delver', [0], { xGte: 150 }),
  },
  {
    index: 8,
    title: ['Crumble Crossing', 'Omló átkelő'],
    hints: [
      [
        'The crumbly strip will not last. Build before it goes.',
        'A morzsás sáv nem tart sokáig. Építs, mielőtt leszakad.',
      ],
    ],
    theme: 'skyreach',
    difficulty: 3,
    ops: [
      rect(SOIL, 0, 460, W, 20),
      rect(SOIL, 0, 380, 140, 20),
      rect(CRUMBLE, 140, 380, 20, 1),
      rect(SOIL, 160, 380, W - 160, 20),
      ...walls,
    ],
    objects: [entrance(40, 370), exitOn(280, 380), water(6, 470, 308, 10)],
    creatures: 10,
    required: 8,
    skills: { mason: 2 },
    minReleaseTicks: 120,
    plan: each('mason', [0], { xGte: 134 }),
  },
  {
    index: 9,
    title: ['Hedge Maze', 'Sövénylabirintus'],
    hints: [['Down first, then through.', 'Előbb le, aztán át.']],
    theme: 'glade',
    difficulty: 4,
    ops: [
      soilFloor,
      rect(SOIL, 0, 380, W, 40),
      rect(METAL, 200, 340, 12, 40),
      rect(SOIL, 240, 420, 16, 20),
      ...walls,
    ],
    objects: [entrance(40, 370), exitOn(285, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 2, burrower: 2 },
    plan: [
      ...each('delver', [0], { xGte: 120 }),
      ...each('burrower', [0], { xGte: 232, yGte: FLOOR }),
    ],
  },
  {
    index: 10,
    title: ['Ember Bridge', 'Parázshíd'],
    hints: [
      ['Bridge the glow, then tunnel the rock.', 'Hidald át az izzást, aztán fúrd át a sziklát.'],
    ],
    theme: 'deep',
    difficulty: 4,
    ops: [rect(ROCK, 0, 400, W, 80), cut(160, 400, 14, 80), rect(ROCK, 240, 340, 14, 60), ...walls],
    objects: [entrance(40, 390), exitOn(290, 400), lava(160, 450, 14, 30)],
    creatures: 10,
    required: 8,
    skills: { mason: 2, burrower: 2 },
    minReleaseTicks: 200,
    plan: [...each('mason', [0], { xGte: 156 }), ...each('burrower', [0], { xGte: 232 })],
  },
  {
    index: 11,
    title: ['Portal Hop', 'Átjáróugrás'],
    hints: [['The portal is behind the wall.', 'Az átjáró a fal mögött van.']],
    theme: 'clockworks',
    difficulty: 4,
    ops: [soilFloor, rect(SOIL, 180, 360, 16, 80), rect(SOIL, 0, 200, 130, 16), ...walls],
    objects: [entrance(40, 430), portal(220, FLOOR, 30, 200), exitOn(100, 200)],
    creatures: 10,
    required: 9,
    skills: { burrower: 2 },
    plan: each('burrower', [0], { xGte: 172 }),
  },
  {
    index: 12,
    title: ['Cloud Hopper', 'Felhőugró'],
    hints: [['Float down, then dig through the cloud.', 'Vitorlázz le, aztán áss át a felhőn.']],
    theme: 'skyreach',
    difficulty: 5,
    ...BIG,
    ops: [
      rect(SOIL, 0, 680, 480, 40),
      rect(SOIL, 0, 240, 150, 12),
      rect(SOIL, 150, 560, 324, 40),
      stamp('cloud', SOIL, 330, 556),
      ...bigWalls,
    ],
    objects: [entrance(50, 230), exitOn(420, 680), water(6, 690, 140, 30)],
    creatures: 15,
    required: 12,
    skills: { glider: 15, delver: 2 },
    minReleaseTicks: 45,
    plan: [...each('glider', range(15)), ...each('delver', [0], { xGte: 260, yGte: 560 })],
  },
  {
    index: 13,
    title: ['Turn Back', 'Visszafordító'],
    hints: [
      ['Someone has to stand guard by the water.', 'Valakinek őrt kell állnia a víz mellett.'],
    ],
    theme: 'glade',
    difficulty: 5,
    ops: [
      soilFloor,
      rect(SOIL, 0, 380, 260, 40),
      cut(260, FLOOR, 54, 40),
      rect(METAL, 254, 420, 6, 20),
      ...walls,
    ],
    objects: [entrance(170, 370, 1), exitOn(50, FLOOR), water(260, 452, 54, 28)],
    creatures: 10,
    required: 8,
    skills: { warden: 2, delver: 2 },
    plan: [
      ...each('warden', [0], { xGte: 220 }),
      ...each('delver', [1], { xLte: 140, dir: -1 }),
      { popAll: true, when: { tick: 2400 } },
    ],
  },
  {
    index: 14,
    title: ['Arrow Maze', 'Nyíllabirintus'],
    hints: [
      ['Arrows only give way in their direction.', 'A nyilak csak a saját irányukba engednek.'],
    ],
    theme: 'deep',
    difficulty: 5,
    ops: [
      rockFloor,
      rect(SOIL, 0, 380, W, 40),
      rect(ONEWAY_R, 120, 340, 16, 40),
      rect(ONEWAY_L, 240, 340, 16, 40),
      ...walls,
    ],
    objects: [entrance(40, 370), exitOn(285, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { burrower: 2, delver: 2 },
    plan: [...each('burrower', [0], { xGte: 112 }), ...each('delver', [0], { xGte: 180 })],
  },
  {
    index: 15,
    title: ['Gear Train', 'Fogaskerékhajtás'],
    hints: [['Bounce up, then dig on.', 'Pattanj fel, aztán áss tovább.']],
    theme: 'clockworks',
    difficulty: 5,
    ops: [
      soilFloor,
      rect(SOIL, 120, 410, W - 120, 30),
      rect(ROCK, 200, 360, 12, 50),
      stamp('gear', METAL, 40, 360),
      ...walls,
    ],
    objects: [entrance(40, 430), padOn(100, FLOOR), exitOn(280, 410)],
    creatures: 10,
    required: 8,
    skills: { burrower: 2 },
    plan: each('burrower', [0], { xGte: 192, yLte: 410 }),
  },
  {
    index: 16,
    title: ['Updraft', 'Felszálló légáram'],
    hints: [['Climb up, glide down.', 'Mássz fel, vitorlázz le.']],
    theme: 'skyreach',
    difficulty: 6,
    ops: [soilFloor, rect(ROCK, 170, 280, 24, 160), ...walls],
    objects: [entrance(40, 430), exitOn(280, FLOOR)],
    creatures: 10,
    required: 7,
    skills: { scaler: 10, glider: 10 },
    minReleaseTicks: 50,
    plan: both(range(10)),
  },
  {
    index: 17,
    title: ['Long Tunnel', 'Hosszú alagút'],
    hints: [['Straight down, then on a slant.', 'Egyenesen le, aztán ferdén.']],
    theme: 'glade',
    difficulty: 6,
    ops: [soilFloor, rect(SOIL, 0, 300, W, 40), rect(ROCK, 0, 360, W, 40), ...walls],
    objects: [entrance(60, 290), exitOn(290, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 2, sloper: 2 },
    plan: [...each('delver', [0], { xGte: 100 }), ...each('sloper', [0], { yGte: 360 })],
  },
  {
    index: 18,
    title: ['Pillar Run', 'Oszlopfutam'],
    hints: [['Four pillars, one tunneller.', 'Négy oszlop, egy fúró.']],
    theme: 'deep',
    difficulty: 6,
    ops: [
      rockFloor,
      rect(ROCK, 90, 410, 12, 30),
      rect(ROCK, 150, 410, 12, 30),
      rect(ROCK, 210, 410, 12, 30),
      rect(ROCK, 260, 410, 12, 30),
      ...walls,
    ],
    objects: [entrance(40, 430), exitOn(298, FLOOR)],
    creatures: 10,
    required: 9,
    skills: { burrower: 5 },
    plan: [
      ...each('burrower', [0], { xGte: 82 }),
      ...each('burrower', [0], { xGte: 142 }),
      ...each('burrower', [0], { xGte: 202 }),
      ...each('burrower', [0], { xGte: 252 }),
    ],
  },
  {
    index: 19,
    title: ['Meeting Point', 'Találkozó'],
    hints: [
      [
        'Both crowds end up in the same shaft – guard the lava side.',
        'Mindkét csapat ugyanabba az aknába kerül – őrizd a láva felőli oldalt.',
      ],
    ],
    theme: 'clockworks',
    difficulty: 7,
    ops: [soilFloor, rect(SOIL, 0, 380, W, 40), cut(6, FLOOR, 60, 40), ...walls],
    objects: [
      entrance(60, 370, 1),
      entrance(260, 370, -1),
      exitOn(170, FLOOR),
      lava(6, 450, 60, 30),
    ],
    creatures: 16,
    required: 13,
    skills: { delver: 2, warden: 2 },
    plan: [
      ...each('delver', [0], { xGte: 140 }),
      ...each('warden', [4], { xLte: 115, yGte: FLOOR }),
      { popAll: true, when: { tick: 3000 } },
    ],
  },
  {
    index: 20,
    title: ['Leaf Rationing', 'Levéljegy'],
    hints: [['Not everyone gets a leaf.', 'Nem kap mindenki levelet.']],
    theme: 'skyreach',
    difficulty: 7,
    ops: [soilFloor, rect(SOIL, 0, 200, 120, 16), ...walls],
    objects: [entrance(40, 190), exitOn(270, FLOOR)],
    creatures: 12,
    required: 8,
    skills: { glider: 9 },
    minReleaseTicks: 50,
    plan: each('glider', range(8)),
  },
  {
    index: 21,
    title: ['Underpass', 'Aluljáró'],
    hints: [['Under the pond, then through the hedge.', 'A tó alatt, aztán át a sövényen.']],
    theme: 'glade',
    difficulty: 7,
    ops: [
      soilFloor,
      rect(SOIL, 0, 360, W, 60),
      cut(150, 360, 60, 20),
      rect(SOIL, 240, 400, 16, 40),
      ...walls,
    ],
    objects: [entrance(40, 350), exitOn(285, FLOOR), water(150, 362, 60, 18)],
    creatures: 10,
    required: 8,
    skills: { sloper: 2, burrower: 2 },
    plan: [
      ...each('sloper', [0], { xGte: 90 }),
      ...each('burrower', [0], { xGte: 232, yGte: FLOOR }),
    ],
  },
  {
    index: 22,
    title: ['Magma Pool', 'Magmamedence'],
    hints: [
      [
        'The first one floats and builds; the rest just float.',
        'Az első vitorlázik és épít, a többiek csak vitorláznak.',
      ],
    ],
    theme: 'deep',
    difficulty: 7,
    ops: [rockFloor, cut(6, FLOOR, 134, 40), rect(ROCK, 0, 260, 120, 16), ...walls],
    objects: [entrance(40, 250), exitOn(280, FLOOR), lava(6, 450, 134, 30)],
    creatures: 10,
    required: 8,
    skills: { mason: 2, glider: 10 },
    minReleaseTicks: 240,
    plan: [
      ...each('glider', [0]),
      ...each('mason', [0], { xGte: 114 }),
      ...each('glider', range(9, 1)),
    ],
  },
  {
    index: 23,
    title: ['Clock Hands', 'Óramutatók'],
    hints: [
      [
        'Speed matters: tunnel twice and send them in a rush.',
        'Számít a sebesség: két alagút, és küldd őket egy csapatban.',
      ],
    ],
    theme: 'clockworks',
    difficulty: 8,
    ops: [soilFloor, rect(ROCK, 120, 360, 24, 80), rect(ROCK, 200, 360, 24, 80), ...walls],
    objects: [entrance(40, 430), trapOn(250, FLOOR), exitOn(290, FLOOR)],
    creatures: 10,
    required: 6,
    skills: { burrower: 3 },
    timeLimitSeconds: 150,
    plan: [
      { release: 15, when: { tick: 0 } },
      ...each('burrower', [0], { xGte: 112 }),
      ...each('burrower', [0], { xGte: 192 }),
    ],
  },
  {
    index: 24,
    title: ['Sky Chimney', 'Égi kémény'],
    hints: [['Up the chimney and out on top.', 'Fel a kéményen, és ki a tetején.']],
    theme: 'skyreach',
    difficulty: 8,
    ops: [soilFloor, rect(ROCK, 160, 270, 12, 170), rect(SOIL, 172, 270, W - 172, 12), ...walls],
    objects: [entrance(40, 430), exitOn(270, 270)],
    creatures: 10,
    required: 8,
    skills: { scaler: 10 },
    minReleaseTicks: 50,
    plan: each('scaler', range(10)),
  },
  {
    index: 25,
    title: ['Bramble Lid', 'Tüskés fedél'],
    hints: [['Stop them first, then pop the lid.', 'Előbb állítsd meg őket, aztán pattintsd fel.']],
    theme: 'glade',
    difficulty: 8,
    ops: [soilFloor, rect(SOIL, 210, 400, W - 210, 10), rect(SOIL, 210, 400, 8, 40), ...walls],
    objects: [entrance(40, 430), exitOn(270, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { warden: 1, popper: 2 },
    plan: [
      ...each('warden', [0], { xGte: 206 }),
      { assign: 'popper', creature: 0, when: { state: 'warden' } },
    ],
  },
  {
    index: 26,
    title: ['Deep Core', 'Mélymag'],
    hints: [
      [
        'Through, down, then on a slant – one Pathling does it all.',
        'Át, le, aztán ferdén – egy Pathling megcsinálja mindet.',
      ],
    ],
    theme: 'deep',
    difficulty: 9,
    ...BIG,
    ops: [
      rect(ROCK, 0, 640, 480, 80),
      rect(SOIL, 0, 470, 480, 40),
      rect(ROCK, 200, 430, 20, 40),
      rect(SOIL, 0, 530, 480, 60),
      rect(METAL, 0, 470, 150, 40),
      ...bigWalls,
    ],
    objects: [entrance(60, 460), exitOn(420, 640)],
    creatures: 15,
    required: 12,
    skills: { burrower: 2, delver: 2, sloper: 2 },
    plan: [
      ...each('burrower', [0], { xGte: 192 }),
      ...each('delver', [0], { xGte: 260 }),
      ...each('sloper', [0], { xGte: 300, yGte: 530 }),
    ],
  },
  {
    index: 27,
    title: ['Express Lift', 'Expresszlift'],
    hints: [['Take the lift, then dig all the way down.', 'Liftezz fel, aztán áss egészen le.']],
    theme: 'clockworks',
    difficulty: 9,
    ...BIG,
    ops: [
      rect(SOIL, 0, 650, 480, 70),
      rect(METAL, 140, 360, 8, 290),
      rect(SOIL, 148, 400, 326, 30),
      rect(SOIL, 148, 460, 326, 30),
      rect(SOIL, 148, 520, 326, 30),
      rect(ROCK, 148, 580, 326, 30),
      ...bigWalls,
    ],
    objects: [entrance(40, 640), portal(100, 650, 180, 400), exitOn(440, 650)],
    creatures: 15,
    required: 13,
    skills: { delver: 4, sloper: 2 },
    plan: [
      ...each('delver', [0], { xGte: 220 }),
      ...each('delver', [0], { xGte: 260, yGte: 460 }),
      ...each('delver', [0], { xGte: 300, yGte: 520 }),
      ...each('sloper', [0], { xGte: 340, yGte: 580 }),
    ],
  },
  {
    index: 28,
    title: ['Glide Path', 'Siklópálya'],
    hints: [
      ['The clouds will not hold. Leaves for all.', 'A felhők nem tartanak. Levelet mindenkinek.'],
    ],
    theme: 'skyreach',
    difficulty: 9,
    ...BIG,
    ops: [
      rect(SOIL, 0, 680, 480, 40),
      rect(SOIL, 0, 240, 160, 12),
      stamp('cloud', SOIL, 50, 236),
      rect(CRUMBLE, 120, 460, 280, 1),
      ...bigWalls,
    ],
    objects: [entrance(50, 230), exitOn(400, 680)],
    creatures: 15,
    required: 12,
    skills: { glider: 15 },
    minReleaseTicks: 45,
    plan: each('glider', range(15)),
  },
  {
    index: 29,
    title: ['Grand Tour', 'Nagy körút'],
    hints: [['Down, through, and down again on a slant.', 'Le, át, aztán megint le, ferdén.']],
    theme: 'glade',
    difficulty: 10,
    ...BIG,
    ops: [
      rect(SOIL, 0, 640, 480, 80),
      rect(SOIL, 0, 470, 480, 40),
      rect(SOIL, 260, 510, 20, 20),
      rect(SOIL, 0, 530, 480, 60),
      ...bigWalls,
    ],
    objects: [entrance(60, 460), exitOn(420, 640)],
    creatures: 15,
    required: 12,
    skills: { delver: 2, burrower: 2, sloper: 2 },
    plan: [
      ...each('delver', [0], { xGte: 160 }),
      ...each('burrower', [0], { xGte: 252, yGte: 530 }),
      ...each('sloper', [0], { xGte: 310, yGte: 530 }),
    ],
  },
  {
    index: 30,
    title: ['Crystal Crown', 'Kristálykorona'],
    hints: [
      [
        'Everyone climbs and glides; one of them opens the floor.',
        'Mindenki mászik és vitorlázik; egyikük megnyitja a padlót.',
      ],
    ],
    theme: 'deep',
    difficulty: 10,
    ...BIG,
    ops: [
      rect(ROCK, 0, 680, 480, 40),
      rect(ROCK, 160, 540, 24, 140),
      rect(METAL, 184, 600, 296, 20),
      rect(SOIL, 350, 600, 60, 20),
      stamp('crystal', ROCK, 100, 673),
      ...bigWalls,
    ],
    objects: [entrance(60, 670), exitOn(440, 680)],
    creatures: 15,
    required: 12,
    skills: { scaler: 15, glider: 15, delver: 2 },
    minReleaseTicks: 50,
    plan: [...both(range(15)), ...each('delver', [0], { xGte: 360, yLte: 600 })],
  },
];
