import type { LevelObject } from '../../src/core/level';
import {
  CRUMBLE,
  type LevelSpec,
  METAL,
  ONEWAY_L,
  ONEWAY_R,
  ROCK,
  SOIL,
  cut,
  each,
  entrance,
  exitOn,
  lava,
  range,
  rect,
  sideWalls,
  stamp,
  water,
} from './build';

/**
 * Bonus pool (§1.3): 30 extra levels in every theme and difficulty 1–10. The daily level picks
 * one of them by date and applies a modifier (`src/core/daily.ts`); the author script records a
 * verified solution for every modifier the reference plan still wins with.
 */

const W = 320;
const FLOOR = 440;
const walls = sideWalls(W, 0, 480);
const soilFloor = rect(SOIL, 0, FLOOR, W, 40);
const rockFloor = rect(ROCK, 0, FLOOR, W, 40);
const BIG = { w: 480, h: 720 };
const bigWalls = sideWalls(480, 0, 720);

function trapOn(x: number, groundY: number): LevelObject {
  return { type: 'trap', x, y: groundY - 10 };
}

function padOn(x: number, groundY: number): LevelObject {
  return { type: 'bounce', x, y: groundY - 4 };
}

function portal(x: number, groundY: number, tx: number, ty: number): LevelObject {
  return { type: 'teleport', x, y: groundY - 12, tx, ty };
}

function both(ids: readonly number[]) {
  return ids.flatMap((i) => [
    { assign: 'scaler' as const, creature: i, when: { state: 'walk' as const } },
    { assign: 'glider' as const, creature: i, when: { state: 'walk' as const } },
  ]);
}

export const BONUS: LevelSpec[] = [
  {
    index: 1,
    theme: 'glade',
    title: ['Garden Gate', 'Kertkapu'],
    hints: [['One hole in the hedge is all it takes.', 'Egyetlen lyuk a sövényen, és kész.']],
    difficulty: 1,
    ops: [soilFloor, rect(SOIL, 180, 370, 24, 70), stamp('bush', SOIL, 60, 436), ...walls],
    objects: [entrance(40, 430), exitOn(280, FLOOR)],
    creatures: 10,
    required: 9,
    skills: { burrower: 2 },
    plan: each('burrower', [0], { xGte: 172 }),
  },
  {
    index: 2,
    theme: 'deep',
    title: ['Basement', 'Pince'],
    hints: [['The way home is straight down.', 'Haza egyenesen lefelé vezet az út.']],
    difficulty: 1,
    ops: [rockFloor, rect(SOIL, 0, 380, W, 40), stamp('stalactite', ROCK, 150, 20), ...walls],
    objects: [entrance(50, 370), exitOn(60, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 2 },
    plan: each('delver', [0], { xGte: 200 }),
  },
  {
    index: 3,
    theme: 'skyreach',
    title: ['Featherfall', 'Tollpihe'],
    hints: [['A leaf for everyone.', 'Levelet mindenkinek.']],
    difficulty: 2,
    ops: [
      rect(SOIL, 0, FLOOR, W, 40),
      rect(SOIL, 0, 160, 140, 14),
      stamp('cloud', SOIL, 200, 120),
      ...walls,
    ],
    objects: [entrance(40, 150), exitOn(260, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { glider: 10 },
    minReleaseTicks: 50,
    plan: each('glider', range(10)),
  },
  {
    index: 4,
    theme: 'clockworks',
    title: ['Overpass', 'Felüljáró'],
    hints: [['Build a bridge over the water.', 'Építs hidat a víz fölé.']],
    difficulty: 2,
    ops: [rect(SOIL, 0, 400, W, 80), cut(190, 400, 16, 80), stamp('cog', METAL, 60, 300), ...walls],
    objects: [entrance(40, 390), exitOn(280, 400), water(190, 450, 16, 30)],
    creatures: 10,
    required: 8,
    skills: { mason: 2 },
    minReleaseTicks: 200,
    plan: each('mason', [0], { xGte: 186 }),
  },
  {
    index: 5,
    theme: 'glade',
    title: ['Rabbit Hole', 'Nyúlüreg'],
    hints: [['Slope down under the pond.', 'Ássatok lejtőt a tavacska alatt.']],
    difficulty: 2,
    ops: [soilFloor, rect(SOIL, 0, 350, W, 70), cut(140, 350, 80, 20), ...walls],
    objects: [entrance(40, 340), exitOn(280, FLOOR), water(140, 352, 80, 18)],
    creatures: 10,
    required: 8,
    skills: { sloper: 2 },
    plan: each('sloper', [0], { xGte: 80 }),
  },
  {
    index: 6,
    theme: 'deep',
    title: ['Detour', 'Kerülő'],
    hints: [
      [
        'They are heading for the lava. Someone has to stand in the way.',
        'A láva felé tartanak. Valakinek az útjukba kell állnia.',
      ],
    ],
    difficulty: 3,
    ops: [rockFloor, cut(6, FLOOR, 64, 40), ...walls],
    objects: [entrance(170, 430, -1), exitOn(280, FLOOR), lava(6, 452, 64, 28)],
    creatures: 10,
    required: 9,
    skills: { warden: 2 },
    plan: [...each('warden', [0], { xLte: 110 }), { popAll: true, when: { tick: 1800 } }],
  },
  {
    index: 7,
    theme: 'clockworks',
    title: ['Rush Hour', 'Csúcsforgalom'],
    hints: [
      [
        'Two traps, one reload time. Hurry them through.',
        'Két csapda, egy újratöltési idő. Siettesd át őket.',
      ],
    ],
    difficulty: 3,
    ops: [soilFloor, stamp('gear', METAL, 140, 340), ...walls],
    objects: [entrance(40, 430), trapOn(150, FLOOR), trapOn(220, FLOOR), exitOn(285, FLOOR)],
    creatures: 12,
    required: 9,
    skills: {},
    plan: [{ release: 15, when: { tick: 0 } }],
  },
  {
    index: 8,
    theme: 'glade',
    title: ['Treetop', 'Lombkorona'],
    hints: [
      ['Climb the trunk – the burrow is up there.', 'Mássz fel a törzsön – fent van az odú.'],
    ],
    difficulty: 3,
    ops: [soilFloor, rect(ROCK, 150, 300, 16, 140), rect(SOIL, 166, 300, W - 166, 12), ...walls],
    objects: [entrance(40, 430), exitOn(260, 300)],
    creatures: 10,
    required: 8,
    skills: { scaler: 10 },
    minReleaseTicks: 50,
    plan: each('scaler', range(10)),
  },
  {
    index: 9,
    theme: 'deep',
    title: ['Stone Slab', 'Kőlap'],
    hints: [
      [
        'The slab is too hard for a Delver. A blast is faster.',
        'A lap túl kemény az Ásónak. Egy robbanás gyorsabb.',
      ],
    ],
    difficulty: 3,
    ops: [rockFloor, rect(ROCK, 0, 380, W, 6), ...walls],
    objects: [entrance(150, 370), exitOn(60, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { popper: 2 },
    plan: each('popper', [0]),
  },
  {
    index: 10,
    theme: 'skyreach',
    title: ['Cloud Stairs', 'Felhőlépcső'],
    hints: [['Two ledges, one builder.', 'Két párkány, egy építő.']],
    difficulty: 4,
    ops: [
      rect(SOIL, 0, FLOOR, W, 40),
      rect(SOIL, 150, 430, W - 150, 10),
      rect(SOIL, 230, 420, W - 230, 10),
      stamp('cloud', SOIL, 40, 200),
      ...walls,
    ],
    objects: [entrance(40, 430), exitOn(290, 420)],
    creatures: 10,
    required: 8,
    skills: { mason: 3 },
    plan: [...each('mason', [0], { xGte: 128 }), ...each('mason', [0], { xGte: 208, yLte: 430 })],
  },
  {
    index: 11,
    theme: 'clockworks',
    title: ['Bypass', 'Elkerülő'],
    hints: [
      [
        'Open the wall and the portal does the rest.',
        'Nyisd meg a falat, a többit elvégzi az átjáró.',
      ],
    ],
    difficulty: 4,
    ops: [soilFloor, rect(SOIL, 120, 360, 16, 80), rect(SOIL, 160, 220, 154, 14), ...walls],
    objects: [entrance(40, 430), portal(200, FLOOR, 180, 220), exitOn(280, 220)],
    creatures: 10,
    required: 9,
    skills: { burrower: 2 },
    plan: each('burrower', [0], { xGte: 112 }),
  },
  {
    index: 12,
    theme: 'deep',
    title: ['Arrow Pit', 'Nyílverem'],
    hints: [
      [
        'Down first, then through the arrows – they only give way to the right.',
        'Előbb le, aztán át a nyilakon – csak jobbra engednek.',
      ],
    ],
    difficulty: 4,
    ops: [rockFloor, rect(SOIL, 0, 380, W, 40), rect(ONEWAY_R, 220, 420, 16, 20), ...walls],
    objects: [entrance(40, 370), exitOn(280, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 2, burrower: 1 },
    plan: [
      ...each('delver', [0], { xGte: 120 }),
      ...each('burrower', [0], { xGte: 212, yGte: FLOOR }),
    ],
  },
  {
    index: 13,
    theme: 'glade',
    title: ['Hollow Log', 'Odvas rönk'],
    hints: [['Float down, then tunnel through the log.', 'Vitorlázz le, aztán fúrj át a rönkön.']],
    difficulty: 4,
    ops: [soilFloor, rect(SOIL, 0, 220, 130, 14), rect(SOIL, 210, 390, 24, 50), ...walls],
    objects: [entrance(40, 210), exitOn(280, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { glider: 10, burrower: 1 },
    minReleaseTicks: 50,
    plan: [...each('glider', range(10)), ...each('burrower', [0], { xGte: 202, yGte: FLOOR })],
  },
  {
    index: 14,
    theme: 'skyreach',
    title: ['Brittle Path', 'Törékeny ösvény'],
    hints: [
      [
        'The crumbling cloud only carries the first ones. Build over it.',
        'Az omladozó felhő csak az elsőket bírja el. Építs fölé.',
      ],
    ],
    difficulty: 5,
    ops: [
      rect(SOIL, 0, 460, W, 20),
      rect(SOIL, 0, 360, 170, 20),
      rect(CRUMBLE, 170, 360, 20, 1),
      rect(SOIL, 190, 360, W - 190, 20),
      ...walls,
    ],
    objects: [entrance(40, 350), exitOn(280, 360), water(6, 470, 308, 10)],
    creatures: 10,
    required: 8,
    skills: { mason: 2 },
    minReleaseTicks: 120,
    plan: each('mason', [0], { xGte: 164 }),
  },
  {
    index: 15,
    theme: 'clockworks',
    title: ['Spring Loaded', 'Felhúzva'],
    hints: [
      [
        'The pad throws them up – the soil wall above is in the way.',
        'A párna feldobja őket – a fenti földfal útban van.',
      ],
    ],
    difficulty: 5,
    ops: [soilFloor, rect(SOIL, 124, 410, W - 124, 30), rect(SOIL, 230, 360, 16, 50), ...walls],
    objects: [entrance(40, 430), padOn(104, FLOOR), exitOn(285, 410)],
    creatures: 10,
    required: 9,
    skills: { burrower: 1 },
    plan: each('burrower', [0], { xGte: 222, yLte: 410 }),
  },
  {
    index: 16,
    theme: 'deep',
    title: ['Mine Cart', 'Csille'],
    hints: [
      [
        'Three layers: soil, rock, soil. Dig them one by one.',
        'Három réteg: föld, kő, föld. Ásd át őket egyenként.',
      ],
    ],
    difficulty: 5,
    ops: [
      rockFloor,
      rect(SOIL, 0, 260, W, 30),
      rect(ROCK, 0, 320, W, 30),
      rect(SOIL, 0, 380, W, 30),
      ...walls,
    ],
    objects: [entrance(60, 250), exitOn(270, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 4 },
    plan: [
      ...each('delver', [0], { xGte: 100 }),
      ...each('delver', [0], { xGte: 150, yGte: 320 }),
      ...each('delver', [0], { xGte: 200, yGte: 380 }),
    ],
  },
  {
    index: 17,
    theme: 'glade',
    title: ['Two Burrows', 'Két odú'],
    hints: [
      [
        'Pathlings come from both sides and meet in the middle.',
        'Mindkét oldalról jönnek, és középen találkoznak.',
      ],
    ],
    difficulty: 5,
    ops: [soilFloor, rect(SOIL, 0, 380, W, 40), ...walls],
    objects: [entrance(50, 370, 1), entrance(270, 370, -1), exitOn(160, FLOOR)],
    creatures: 16,
    required: 14,
    skills: { delver: 2 },
    plan: each('delver', [0], { xGte: 135 }),
  },
  {
    index: 18,
    theme: 'skyreach',
    title: ['Summit', 'Csúcs'],
    hints: [
      ['Climb up, then float down the far side.', 'Mássz fel, aztán vitorlázz le a túloldalon.'],
    ],
    difficulty: 6,
    ops: [rect(SOIL, 0, FLOOR, W, 40), rect(ROCK, 140, 260, 30, 180), ...walls],
    objects: [entrance(40, 430), exitOn(280, FLOOR)],
    creatures: 10,
    required: 7,
    skills: { scaler: 10, glider: 10 },
    minReleaseTicks: 50,
    plan: both(range(10)),
  },
  {
    index: 19,
    theme: 'clockworks',
    title: ['Gearbox', 'Sebességváltó'],
    hints: [
      [
        'Rush them past the trap, and mind the rock wall.',
        'Siettesd el őket a csapda mellett, és vigyázz a kőfalra.',
      ],
    ],
    difficulty: 6,
    ops: [soilFloor, rect(ROCK, 100, 360, 16, 80), stamp('cog', METAL, 200, 330), ...walls],
    objects: [entrance(40, 430), trapOn(200, FLOOR), exitOn(285, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { burrower: 2 },
    plan: [{ release: 15, when: { tick: 0 } }, ...each('burrower', [0], { xGte: 92 })],
  },
  {
    index: 20,
    theme: 'deep',
    title: ['Ember Bridge', 'Parázshíd'],
    hints: [
      [
        'Float down past the lava lake – but someone must bridge it first.',
        'Vitorlázz le a lávató mellett – de előbb valakinek hidat kell vernie.',
      ],
    ],
    difficulty: 6,
    ops: [rockFloor, cut(6, FLOOR, 124, 40), rect(ROCK, 0, 280, 110, 16), ...walls],
    objects: [entrance(40, 270), exitOn(280, FLOOR), lava(6, 450, 124, 30)],
    creatures: 10,
    required: 8,
    skills: { mason: 1, glider: 10 },
    minReleaseTicks: 240,
    plan: [
      ...each('glider', [0]),
      ...each('mason', [0], { xGte: 104 }),
      ...each('glider', range(9, 1)),
    ],
  },
  {
    index: 21,
    theme: 'glade',
    title: ['Roots', 'Gyökerek'],
    hints: [
      [
        'Down, sideways, down again: one pioneer does it all.',
        'Le, oldalra, megint le: egy úttörő mindent megold.',
      ],
    ],
    difficulty: 6,
    ...BIG,
    ops: [
      rect(SOIL, 0, 640, 480, 80),
      rect(SOIL, 0, 450, 480, 40),
      rect(ROCK, 260, 490, 20, 20),
      rect(SOIL, 0, 510, 480, 80),
      ...bigWalls,
    ],
    objects: [entrance(60, 440), exitOn(420, 640)],
    creatures: 15,
    required: 12,
    skills: { delver: 1, burrower: 2, sloper: 1 },
    plan: [
      ...each('delver', [0], { xGte: 160 }),
      ...each('burrower', [0], { xGte: 252, yGte: 510 }),
      ...each('sloper', [0], { xGte: 310, yGte: 510 }),
    ],
  },
  {
    index: 22,
    theme: 'skyreach',
    title: ['Cliff Dive', 'Szirtugrás'],
    hints: [['Only seven leaves for ten Pathlings.', 'Csak hét levél jut tíz Pathlingre.']],
    difficulty: 7,
    ops: [rect(SOIL, 0, FLOOR, W, 40), rect(SOIL, 0, 200, 110, 16), ...walls],
    objects: [entrance(40, 190), exitOn(270, FLOOR)],
    creatures: 10,
    required: 7,
    skills: { glider: 7 },
    minReleaseTicks: 50,
    plan: each('glider', range(7)),
  },
  {
    index: 23,
    theme: 'clockworks',
    title: ['Pressure Plate', 'Nyomólap'],
    hints: [
      [
        'Stand guard before the trap, then pop the guard when the time is right.',
        'Állíts őrt a csapda elé, aztán a megfelelő pillanatban pukkantsd ki.',
      ],
    ],
    difficulty: 7,
    ops: [soilFloor, rect(METAL, 120, FLOOR, 40, 6), rect(METAL, 70, 400, 6, 40), ...walls],
    objects: [entrance(100, 430), trapOn(230, FLOOR), exitOn(285, FLOOR)],
    creatures: 10,
    required: 7,
    skills: { warden: 1, popper: 1 },
    minReleaseTicks: 90,
    plan: [
      ...each('warden', [0], { xGte: 140 }),
      { release: 23, when: { tick: 0 } },
      { assign: 'popper', creature: 0, when: { tick: 300, state: 'warden' } },
    ],
  },
  {
    index: 24,
    theme: 'deep',
    title: ['Vault Door', 'Páncélajtó'],
    hints: [
      [
        'Climb into the vault, then dig through its soft roof.',
        'Mássz be a páncélterembe, aztán áss át a puha tetején.',
      ],
    ],
    difficulty: 7,
    ops: [
      rockFloor,
      rect(METAL, 180, 380, 8, 60),
      rect(METAL, 306, 380, 8, 60),
      rect(SOIL, 180, 380, 134, 10),
      ...walls,
    ],
    objects: [entrance(40, 430), exitOn(250, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { scaler: 10, delver: 2 },
    minReleaseTicks: 50,
    plan: [...each('scaler', range(10)), ...each('delver', [0], { xGte: 230, yLte: 380 })],
  },
  {
    index: 25,
    theme: 'skyreach',
    title: ['Falling Sky', 'Leszakadó ég'],
    hints: [
      [
        'Leaves first – and dig through the cloud bank below.',
        'Előbb levelek – aztán áss át a lenti felhőpadon.',
      ],
    ],
    difficulty: 8,
    ...BIG,
    ops: [
      rect(SOIL, 0, 680, 480, 40),
      rect(SOIL, 0, 200, 140, 12),
      rect(SOIL, 140, 540, 334, 40),
      stamp('cloud', SOIL, 260, 536),
      ...bigWalls,
    ],
    objects: [entrance(50, 190), exitOn(420, 680), water(6, 690, 130, 30)],
    creatures: 15,
    required: 12,
    skills: { glider: 15, delver: 1 },
    minReleaseTicks: 45,
    plan: [...each('glider', range(15)), ...each('delver', [0], { xGte: 200, yGte: 540 })],
  },
  {
    index: 26,
    theme: 'clockworks',
    title: ['Crossed Wires', 'Keresztbe kötve'],
    hints: [
      [
        'Turn them around at the lava, then open the arrow wall.',
        'Fordítsd vissza őket a lávánál, aztán nyisd meg a nyílfalat.',
      ],
    ],
    difficulty: 8,
    ops: [soilFloor, cut(6, FLOOR, 74, 40), rect(ONEWAY_R, 230, 360, 16, 80), ...walls],
    objects: [entrance(190, 430, -1), exitOn(290, FLOOR), lava(6, 452, 74, 28)],
    creatures: 10,
    required: 8,
    skills: { warden: 1, burrower: 1 },
    plan: [
      ...each('warden', [0], { xLte: 120 }),
      ...each('burrower', [1], { xGte: 222, dir: 1 }),
      { popAll: true, when: { tick: 2600 } },
    ],
  },
  {
    index: 27,
    theme: 'deep',
    title: ['Left Turn', 'Balkanyar'],
    hints: [
      [
        'The arrows only open to the left – and the metal never does.',
        'A nyilak csak balra nyílnak – a fém pedig sosem.',
      ],
    ],
    difficulty: 8,
    ops: [rockFloor, rect(ONEWAY_L, 90, 360, 16, 80), rect(METAL, 210, 360, 8, 80), ...walls],
    objects: [entrance(160, 430), exitOn(40, FLOOR)],
    creatures: 10,
    required: 9,
    skills: { burrower: 2 },
    plan: each('burrower', [0], { xLte: 114, dir: -1 }),
  },
  {
    index: 28,
    theme: 'skyreach',
    title: ['Thin Air', 'Ritka levegő'],
    hints: [
      [
        'Climb the spire, glide over the gap, and the crumble does not matter.',
        'Mássz fel a csúcsra, siklj át a résen, és nem számít az omladék.',
      ],
    ],
    difficulty: 9,
    ops: [
      rect(SOIL, 0, FLOOR, W, 40),
      rect(ROCK, 160, 290, 20, 150),
      rect(CRUMBLE, 160, 280, 20, 10),
      ...walls,
    ],
    objects: [entrance(40, 430), exitOn(285, FLOOR)],
    creatures: 10,
    required: 7,
    skills: { scaler: 10, glider: 10 },
    minReleaseTicks: 50,
    plan: both(range(10)),
  },
  {
    index: 29,
    theme: 'clockworks',
    title: ['Clock Tower', 'Óratorony'],
    hints: [
      [
        'Each portal leads one floor up. Open the way on every floor.',
        'Minden átjáró egy emelettel feljebb visz. Nyisd meg az utat minden szinten.',
      ],
    ],
    difficulty: 9,
    ...BIG,
    ops: [
      rect(SOIL, 0, 680, 480, 40),
      rect(SOIL, 140, 600, 16, 80),
      rect(SOIL, 0, 420, 480, 30),
      rect(SOIL, 0, 250, 480, 30),
      rect(SOIL, 320, 240, 154, 10),
      ...bigWalls,
    ],
    objects: [
      entrance(40, 670),
      portal(220, 680, 40, 420),
      exitOn(430, 240),
      { type: 'teleport', x: 396, y: 468, tx: 40, ty: 250 },
    ],
    creatures: 15,
    required: 13,
    skills: { burrower: 1, delver: 1, mason: 2 },
    plan: [
      ...each('burrower', [0], { xGte: 132 }),
      ...each('delver', [0], { xGte: 401, yLte: 420, yGte: 420 }),
      ...each('mason', [0], { xGte: 298, yLte: 250 }),
    ],
  },
  {
    index: 30,
    theme: 'glade',
    title: ['Grand Tour', 'Nagy körút'],
    hints: [
      [
        'Leaves for all, a staircase over the pond and a tunnel at the end.',
        'Levél mindenkinek, lépcső a tó fölött és alagút a végén.',
      ],
      [
        'The first Pathling does all the building and digging.',
        'Az első Pathling végzi az összes építést és ásást.',
      ],
    ],
    difficulty: 10,
    ...BIG,
    ops: [
      rect(SOIL, 0, 680, 480, 40),
      rect(SOIL, 0, 260, 150, 16),
      cut(220, 680, 14, 40),
      rect(SOIL, 380, 620, 20, 60),
      stamp('tree', SOIL, 60, 180),
      ...bigWalls,
    ],
    objects: [entrance(50, 250), exitOn(440, 680), water(220, 690, 14, 30)],
    creatures: 15,
    required: 12,
    skills: { glider: 15, mason: 1, burrower: 1 },
    minReleaseTicks: 120,
    plan: [
      ...each('glider', range(15)),
      ...each('mason', [0], { xGte: 216, yGte: 680 }),
      ...each('burrower', [0], { xGte: 372, yGte: 680 }),
    ],
  },
];
