import {
  type LevelSpec,
  METAL,
  ONEWAY_L,
  ONEWAY_R,
  ROCK,
  SOIL,
  cut,
  each,
  entrance,
  exitOn,
  lava,
  range,
  rect,
  sideWalls,
  stamp,
} from './build';

/**
 * World 2 – Crystal Deep (§1.3): rock (slow to dig), metal (never dug), one-way walls (arrows
 * show the only direction they can be dug sideways), lava and tall vertical shafts.
 * Difficulty 3–8. Rule of thumb: a shaft's top is never more than 60 px above the next floor.
 */

const W = 320;
const FLOOR = 440;
const walls = sideWalls(W, 0, 480);
const floor = rect(ROCK, 0, FLOOR, W, 40);
const BIG = { w: 480, h: 720 };
const bigWalls = sideWalls(480, 0, 720);

export const W2: LevelSpec[] = [
  {
    index: 1,
    title: ['Crystal Steps', 'Kristálylépcső'],
    hints: [['Rock digs slowly – but it digs.', 'A kő lassan ásható – de ásható.']],
    difficulty: 3,
    ops: [floor, rect(ROCK, 0, 380, W, 40), stamp('crystal', SOIL, 250, 373), ...walls],
    objects: [entrance(60, 370), exitOn(270, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 2 },
    plan: each('delver', [0], { xGte: 120 }),
  },
  {
    index: 2,
    title: ['Metal Floor', 'Fémpadló'],
    hints: [
      [
        'Metal can never be dug. Find the soft spot.',
        'A fémet sosem lehet kiásni. Keresd a puha részt.',
      ],
    ],
    difficulty: 3,
    ops: [floor, rect(METAL, 0, 380, 200, 40), rect(SOIL, 200, 380, W - 200, 40), ...walls],
    objects: [entrance(60, 370), exitOn(60, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 1 },
    plan: each('delver', [0], { xGte: 222 }),
  },
  {
    index: 3,
    title: ['Arrow Wall', 'Nyílfal'],
    hints: [
      [
        'The arrows show the only way this wall can be dug sideways.',
        'A nyilak mutatják az egyetlen irányt, amerre ez a fal oldalra ásható.',
      ],
    ],
    difficulty: 3,
    ops: [floor, rect(ONEWAY_R, 150, 360, 16, 80), ...walls],
    objects: [entrance(40, 430), exitOn(280, FLOOR)],
    creatures: 10,
    required: 9,
    skills: { burrower: 2 },
    plan: each('burrower', [0], { xGte: 142 }),
  },
  {
    index: 4,
    title: ['Lava Moat', 'Lávaárok'],
    hints: [
      [
        'Lava is as deadly as water. Bridge it right at the edge.',
        'A láva ugyanolyan halálos, mint a víz. Hidald át pont a szélén.',
      ],
    ],
    difficulty: 4,
    ops: [rect(ROCK, 0, 400, W, 80), cut(200, 400, 14, 80), ...walls],
    objects: [entrance(40, 390), exitOn(280, 400), lava(200, 450, 14, 30)],
    creatures: 10,
    required: 8,
    skills: { mason: 1 },
    minReleaseTicks: 200,
    plan: each('mason', [0], { xGte: 196 }),
  },
  {
    index: 5,
    title: ['The Shaft', 'Az akna'],
    hints: [
      [
        'Four floors to the bottom – never dig twice in the same spot.',
        'Négy szint az aljáig – sose áss kétszer ugyanott.',
      ],
    ],
    difficulty: 4,
    ops: [
      floor,
      rect(SOIL, 0, 200, W, 30),
      rect(SOIL, 0, 260, W, 30),
      rect(ROCK, 0, 320, W, 30),
      rect(SOIL, 0, 380, W, 30),
      ...walls,
    ],
    objects: [entrance(60, 190), exitOn(270, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 4 },
    plan: [
      ...each('delver', [0], { xGte: 100 }),
      ...each('delver', [0], { xGte: 140, yGte: 260 }),
      ...each('delver', [0], { xGte: 180, yGte: 320 }),
      ...each('delver', [0], { xGte: 220, yGte: 380 }),
    ],
  },
  {
    index: 6,
    title: ['Rock Hard', 'Kőkemény'],
    hints: [
      [
        'A thick rock wall and little time. Start early.',
        'Vastag kőfal és kevés idő. Kezdj korán.',
      ],
    ],
    difficulty: 4,
    ops: [floor, rect(ROCK, 140, 360, 40, 80), ...walls],
    objects: [entrance(40, 430), exitOn(280, FLOOR)],
    creatures: 10,
    required: 9,
    skills: { burrower: 1 },
    timeLimitSeconds: 150,
    plan: each('burrower', [0], { xGte: 132 }),
  },
  {
    index: 7,
    title: ['Turnabout', 'Fordulat'],
    hints: [
      [
        'They head for the lava. Turn them, then dig the way the arrows point.',
        'A láva felé tartanak. Fordítsd vissza őket, aztán áss a nyilak irányába.',
      ],
    ],
    difficulty: 5,
    ops: [floor, cut(6, FLOOR, 74, 40), rect(ONEWAY_R, 240, 360, 16, 80), ...walls],
    objects: [entrance(200, 430, -1), exitOn(290, FLOOR), lava(6, 452, 74, 28)],
    creatures: 10,
    required: 8,
    skills: { warden: 1, burrower: 1 },
    plan: [
      ...each('warden', [0], { xLte: 120 }),
      ...each('burrower', [1], { xGte: 232, dir: 1 }),
      { popAll: true, when: { tick: 2600 } },
    ],
  },
  {
    index: 8,
    title: ['Wrong Side', 'A rossz oldal'],
    hints: [
      [
        'Arrows only stop sideways digging. Going down is always allowed.',
        'A nyilak csak az oldalirányú ásást tiltják. Lefelé mindig szabad.',
      ],
    ],
    difficulty: 5,
    ops: [
      floor,
      rect(SOIL, 0, 380, W, 40),
      rect(ONEWAY_L, 180, 340, 16, 40),
      rect(ROCK, 220, 420, 16, 20),
      ...walls,
    ],
    objects: [entrance(40, 370), exitOn(280, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 1, burrower: 1 },
    plan: [
      ...each('delver', [0], { xGte: 120 }),
      ...each('burrower', [0], { xGte: 212, yGte: FLOOR }),
    ],
  },
  {
    index: 9,
    title: ['Glowing Depths', 'Izzó mélység'],
    hints: [
      [
        'A long fall into the cave – and a rock wall at the bottom.',
        'Hosszú zuhanás a barlangba – és egy kőfal az alján.',
      ],
    ],
    difficulty: 5,
    ...BIG,
    ops: [
      rect(ROCK, 0, 680, 480, 40),
      rect(ROCK, 0, 300, 160, 16),
      rect(ROCK, 300, 620, 20, 60),
      cut(6, 680, 90, 40),
      stamp('cluster', ROCK, 380, 674),
      ...bigWalls,
    ],
    objects: [entrance(60, 290), exitOn(430, 680), lava(6, 690, 90, 30)],
    creatures: 15,
    required: 12,
    skills: { glider: 15, burrower: 1 },
    minReleaseTicks: 45,
    plan: [...each('glider', range(15)), ...each('burrower', [0], { xGte: 292, yGte: 680 })],
  },
  {
    index: 10,
    title: ['Metal Mesh', 'Fémháló'],
    hints: [
      [
        'Two soft spots in the metal – only one leads home.',
        'Két puha folt a fémben – csak az egyik vezet haza.',
      ],
    ],
    difficulty: 5,
    ops: [
      floor,
      rect(METAL, 0, 380, W, 40),
      rect(SOIL, 80, 380, 40, 40),
      rect(SOIL, 240, 380, 40, 40),
      rect(METAL, 200, 400, 8, 40),
      ...walls,
    ],
    objects: [entrance(40, 370), exitOn(270, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { delver: 2 },
    plan: each('delver', [0], { xGte: 252 }),
  },
  {
    index: 11,
    title: ['Lava Lake', 'Lávató'],
    hints: [
      [
        'Build out over the lava first, then float down beyond it.',
        'Előbb építs ki a láva fölé, aztán vitorlázz le a túloldalra.',
      ],
    ],
    difficulty: 6,
    ops: [floor, cut(6, FLOOR, 134, 40), rect(ROCK, 0, 280, 120, 16), ...walls],
    objects: [entrance(40, 270), exitOn(280, FLOOR), lava(6, 450, 134, 30)],
    creatures: 10,
    required: 8,
    skills: { mason: 1, glider: 10 },
    minReleaseTicks: 240,
    plan: [
      ...each('glider', [0]),
      ...each('mason', [0], { xGte: 114 }),
      ...each('glider', range(9, 1)),
    ],
  },
  {
    index: 12,
    title: ['Pillars', 'Oszlopsor'],
    hints: [['One Burrower, three pillars.', 'Egy Fúró, három oszlop.']],
    difficulty: 6,
    ops: [
      floor,
      rect(ROCK, 100, 410, 12, 30),
      rect(ROCK, 170, 410, 12, 30),
      rect(ROCK, 240, 410, 12, 30),
      ...walls,
    ],
    objects: [entrance(40, 430), exitOn(290, FLOOR)],
    creatures: 10,
    required: 9,
    skills: { burrower: 3 },
    plan: [
      ...each('burrower', [0], { xGte: 92 }),
      ...each('burrower', [0], { xGte: 162 }),
      ...each('burrower', [0], { xGte: 232 }),
    ],
  },
  {
    index: 13,
    title: ['Sealed Vault', 'Lezárt kamra'],
    hints: [
      [
        'The vault has metal walls but a soft roof. Climb up, then dig in.',
        'A kamra fala fém, de a teteje puha. Mássz fel, aztán áss be.',
      ],
    ],
    difficulty: 6,
    ops: [
      floor,
      rect(METAL, 200, 380, 8, 60),
      rect(METAL, 306, 380, 8, 60),
      rect(SOIL, 200, 380, 114, 10),
      ...walls,
    ],
    objects: [entrance(40, 430), exitOn(260, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { scaler: 10, delver: 1 },
    minReleaseTicks: 50,
    plan: [...each('scaler', range(10)), ...each('delver', [0], { xGte: 240, yLte: 380 })],
  },
  {
    index: 14,
    title: ['Twin Arrows', 'Ikernyilak'],
    hints: [
      [
        'The first wall lets you through, the second does not – go under it.',
        'Az első fal átenged, a második nem – menj alatta.',
      ],
    ],
    difficulty: 7,
    ops: [
      floor,
      rect(SOIL, 0, 380, W, 40),
      rect(ONEWAY_R, 100, 340, 16, 40),
      rect(ONEWAY_L, 220, 340, 16, 40),
      ...walls,
    ],
    objects: [entrance(40, 370), exitOn(280, FLOOR)],
    creatures: 10,
    required: 8,
    skills: { burrower: 1, delver: 1 },
    plan: [...each('burrower', [0], { xGte: 92 }), ...each('delver', [0], { xGte: 160 })],
  },
  {
    index: 15,
    title: ['Lava Run', 'Lávafutam'],
    hints: [
      ['Dig under the lava pool – and dig deep enough.', 'Áss a lávató alá – és elég mélyre.'],
    ],
    difficulty: 7,
    ops: [floor, rect(ROCK, 0, 360, W, 60), cut(130, 360, 70, 16), ...walls],
    objects: [entrance(40, 350), exitOn(280, FLOOR), lava(130, 362, 70, 14)],
    creatures: 10,
    required: 8,
    skills: { sloper: 1 },
    plan: each('sloper', [0], { xGte: 70 }),
  },
  {
    index: 16,
    title: ['Deep Drop', 'Mély zuhanás'],
    hints: [
      [
        'Dig through the shelf – but the cave below is far too deep to fall into.',
        'Áss át a polcon – de az alatta lévő barlang túl mély a zuhanáshoz.',
      ],
    ],
    difficulty: 7,
    ...BIG,
    ops: [rect(ROCK, 0, 680, 480, 40), rect(SOIL, 0, 300, 480, 40), ...bigWalls],
    objects: [entrance(60, 290), exitOn(420, 680)],
    creatures: 15,
    required: 12,
    skills: { glider: 15, delver: 1 },
    minReleaseTicks: 45,
    plan: [...each('glider', range(15)), ...each('delver', [0], { xGte: 160 })],
  },
  {
    index: 17,
    title: ['Narrow Ledges', 'Keskeny párkányok'],
    hints: [['Two ledges, one Mason, lava below.', 'Két párkány, egy Kőműves, alatta láva.']],
    difficulty: 7,
    ops: [
      floor,
      rect(ROCK, 160, 430, W - 160, 10),
      rect(ROCK, 240, 420, W - 240, 10),
      cut(100, FLOOR, 40, 40),
      ...walls,
    ],
    objects: [entrance(170, 420, -1), exitOn(290, 420), lava(100, 452, 40, 28)],
    creatures: 10,
    required: 8,
    skills: { mason: 2, warden: 1 },
    plan: [
      ...each('warden', [0], { xLte: 160 }),
      ...each('mason', [1], { xGte: 218, yLte: 430, dir: 1 }),
      { popAll: true, when: { tick: 2800 } },
    ],
  },
  {
    index: 18,
    title: ['The Core', 'A mag'],
    hints: [
      [
        'Sideways, down, then diagonally down – in that order.',
        'Oldalra, le, aztán ferdén le – ebben a sorrendben.',
      ],
    ],
    difficulty: 8,
    ...BIG,
    ops: [
      rect(ROCK, 0, 640, 480, 80),
      rect(SOIL, 0, 470, 480, 40),
      rect(ROCK, 160, 430, 20, 40),
      rect(SOIL, 0, 530, 480, 60),
      rect(METAL, 0, 470, 120, 40),
      ...bigWalls,
    ],
    objects: [entrance(60, 460), exitOn(420, 640)],
    creatures: 15,
    required: 12,
    skills: { burrower: 1, delver: 1, sloper: 1 },
    plan: [
      ...each('burrower', [0], { xGte: 152 }),
      ...each('delver', [0], { xGte: 220 }),
      ...each('sloper', [0], { xGte: 260, yGte: 530 }),
    ],
  },
  {
    index: 19,
    title: ['Arrow Gauntlet', 'Nyílpróba'],
    hints: [
      [
        'Turn them around: these arrows only open from the right.',
        'Fordítsd meg őket: ezek a nyilak csak jobbról nyílnak.',
      ],
    ],
    difficulty: 8,
    ops: [floor, rect(ONEWAY_L, 100, 360, 16, 80), rect(METAL, 200, 360, 8, 80), ...walls],
    objects: [entrance(150, 430), exitOn(40, FLOOR)],
    creatures: 10,
    required: 9,
    skills: { burrower: 1 },
    plan: each('burrower', [0], { xLte: 124, dir: -1 }),
  },
  {
    index: 20,
    title: ['Crystal Heart', 'Kristályszív'],
    hints: [
      [
        'Climb, float, dig – every Pathling needs to climb and float.',
        'Mászás, vitorlázás, ásás – minden Pathlingnek másznia és vitorláznia kell.',
      ],
      ['Dig the shaft where the rock ends.', 'Ott áss aknát, ahol véget ér a kő.'],
    ],
    difficulty: 8,
    ...BIG,
    ops: [
      rect(ROCK, 0, 680, 480, 40),
      rect(ROCK, 140, 540, 24, 140),
      rect(METAL, 164, 600, 316, 20),
      rect(SOIL, 330, 600, 60, 20),
      stamp('crystal', ROCK, 100, 673),
      ...bigWalls,
    ],
    objects: [entrance(60, 670), exitOn(430, 680)],
    creatures: 15,
    required: 12,
    skills: { scaler: 15, glider: 15, delver: 1 },
    minReleaseTicks: 50,
    plan: [
      ...range(15).flatMap((i) => [
        { assign: 'scaler' as const, creature: i, when: { state: 'walk' as const } },
        { assign: 'glider' as const, creature: i, when: { state: 'walk' as const } },
      ]),
      ...each('delver', [0], { xGte: 340, yLte: 600 }),
    ],
  },
];
