import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { loadLevelCode } from '../../src/core/code/verify';

/**
 * T9.4: level codes are a promise to players – codes generated by the M4 build (commit
 * ae8df6a, `tests/fixtures/levelCodes-m4.json`) must still decode and verify byte for byte.
 */
const fixture = JSON.parse(
  readFileSync(join(import.meta.dirname, '../fixtures/levelCodes-m4.json'), 'utf8'),
) as { commit: string; simVersion: number; codes: Record<string, string> };

describe('level-code compatibility', () => {
  it('has codes from the M4 build', () => {
    expect(Object.keys(fixture.codes).length).toBeGreaterThanOrEqual(5);
  });

  for (const [id, code] of Object.entries(fixture.codes)) {
    it(`${id}: an M4 code still loads as verified`, () => {
      const { level, verify } = loadLevelCode(code);
      expect(verify.status).toBe('verified');
      expect(level.author).toBe('M4');
    });
  }
});
